version: "3.1"
services:
  wp-test-www:
    build: ./docker/server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    links:
      - wp-test-db
    networks:
      - default
  wp-test-db:
    image: mysql:5.7
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_DATABASE: test_wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  wp-test-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - wp-test-db:db
    ports:
      - 8090:80
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  persistent: